# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 100000
        min-spare-threads: 3000
    port: 8080
    servlet:
      context-path: /plate-service
      session:
        timeout: 72000s

# mysql
spring:
    application:
      name: plate-service
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    # ָ����̬��Դ��·��
    resources:
        static-locations: classpath:/static/,classpath:/view/
    devtools:
        restart:
           enabled: true
           exclude: view/**
#    redis:
#        open: false  # �Ƿ���redis����  true����   false�ر�
#        database: 0
#        host: localhost
#        port: 16379
#        password:       # ���루Ĭ��Ϊ�գ�
#        timeout: 6000  # ���ӳ�ʱʱ�������룩
#        pool:
#            max-active: 1000  # ���ӳ������������ʹ�ø�ֵ��ʾû�����ƣ�
#            max-wait: -1      # ���ӳ���������ȴ�ʱ�䣨ʹ�ø�ֵ��ʾû�����ƣ�
#            max-idle: 10      # ���ӳ��е�����������
#            min-idle: 5       # ���ӳ��е���С��������
    datasource:
        url: jdbc:mysql://107.172.77.191:3306/k_plate?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root123
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
          initial-size: 10
          max-active: 100
          min-idle: 10
          max-wait: 60000
          query-timeout: 6000



# Mybatis����
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml

###################  mybatis-plus����  ###################
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    id-type: 0  #0:���ݿ�ID����   1:�û�����id  2:ȫ��Ψһid(IdWorker)  3:ȫ��ΨһID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #���õĻ����ȫ�ֿ���
    lazyLoadingEnabled: true #��ʱ���صĿ���
    multipleResultSetsEnabled: true #�����Ļ�����ʱ����һ������ʱ����ظö���ȫ�����ԣ��������������



